config/routes.rb
Rails.application.routes.draw do
  resources :beers

  root 'beers#home'

end

app/models/beer.rb
class Beer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
	before_action :set_beer, only: [:show, :edit, :update, :destroy]

	def home
	end

	def index
		@beers = Beer.all
	end

	def show
	end

	def new
		@beer = Beer.new
	end

	def edit
	end

	def create
    @beer = Beer.new(beer_params)
    respond_to do |format|
      		if @beer.save
        		format.html { redirect_to @beer, notice: 'Beer was successfully created.' }
        		format.json { render :show, status: :created, location: @beer }
      		else
        		format.html { render :new }
        		format.json { render json: @beer.errors, status: :unprocessable_entity }
      		end
    	end
	end

	def update
		respond_to do |format|
      		if @beer.update(beer_params)
        		format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
       		    format.json { render :show, status: :ok, location: @beer }
      		else
        		format.html { render :edit }
        		format.json { render json: @beers.errors, status: :unprocessable_entity }
      		end
    	end
	end

	def destroy
		@beer.destroy
    	respond_to do |format|
      	format.html { redirect_to @beer, notice: 'Beer was successfully destroyed.' }
      	format.json { head :no_content }
    end
	end

	private
    # Use callbacks to share common setup or constraints between actions.
    	def set_beer
      		@beer = Beer.find(params[:id])
    	end

    # Never trust parameters from the scary internet, only allow the white list through.
    	def beer_params
      		params.require(:beer).permit(:name, :description, :image)
    	end
	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>

  <% end %>

app/views/beers/edit.html.erb
<h1>Editing Beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>
<%= link_to 'Delete', @beer %>

app/views/beers/home.html.erb
<div class="jumbotron">

		<h1> Rabbit Hole Brew Shop!</h1>

		<%= image_tag 'beer_home.jpg' %>
		<br>

		<center><%= link_to "Take a look at our Brews!", beers_path, class: "btn btn-default" %></center>

</div>

app/views/beers/index.html.erb
<h1>Daaaaaa Beers!</h1>
<div class="row">
  <% @beers.each do |beer| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="<%= beer.image %>">
      <div class="caption">
          <h3><%= beer.name %></h3>
          <h4><%= beer.description %></h4>
          <%= link_to "More Info", beer, class:"btn btn-default" %>
      </div>
    </div>
  </div>
<% end %>

</div>

<center><%= link_to "Add Beer", new_beer_path, class:"btn btn-primary" %></center>

app/views/beers/new.html.erb
<h1>New Beer</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<div class="jumbotron">
<div class="brews">
  <center>
    <h1><%= @beer.name %></h1>
    <img src="<%= @beer.image %>">
  </center>

  <h3><em>Description:</em> <%= @beer.description %></h3>
 </div>
</div>

<%= link_to 'Edit', edit_beer_path(@beer), class:"btn btn-primary" %> 
<%= link_to 'Back', beers_path, class:"btn btn-primary"%>
<%= link_to 'Delete', @beer, class:"btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeerPub</title>

  <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>